# Generated by Django 5.1.6 on 2025-04-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='demand_variability',
            field=models.FloatField(default=0.1, help_text='Demand variability (0-1)'),
        ),
        migrations.AddField(
            model_name='product',
            name='lead_time',
            field=models.IntegerField(default=7, help_text='Lead time in days'),
        ),
        migrations.AddField(
            model_name='product',
            name='service_level',
            field=models.FloatField(default=0.95, help_text='Desired service level (0-1)'),
        ),
    ]
