# Generated by Django 5.1.6 on 2025-04-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_product_demand_variability_product_lead_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='demand_variability',
        ),
        migrations.RemoveField(
            model_name='product',
            name='service_level',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('A', 'High Value'), ('B', 'Medium Value'), ('C', 'Low Value')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='lead_time',
            field=models.IntegerField(default=7),
        ),
    ]
